import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Container from '@/components/container/Container'
import Provider from '@/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark" className="transition-all">
      <body className={inter.className}>
        <Provider>
          <Container>
            <div className='flex min-h-screen flex-col justify-between '>
              <div>
                <Navbar></Navbar>
                <main className='mt-10 md:mt-0 p-4'>
                  {children}
                </main>
              </div>
              <footer>I am footer</footer>
            </div>
          </Container>
        </Provider>

      </body>
    </html>
  )
}
